version: '2'
services:
   domoticz:
      build: .
      container_name: domoticz
      image: tgiesela/domoticz:0.1
      hostname: domoticz
      domainname: thuis.local
      ports:
         - "8080:8080"   # web gui
      privileged: true
      volumes:
        - /dev/bus/usb:/dev/bus/usb
      network_mode: "host"
      environment:
        - TZ=Europe/Amsterdam
      restart: always

